language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install .
  - pip install flake8 pylint coveralls cryptography pycryptodome
script:
- flake8 aio_adb_shell/ && pylint aio_adb_shell/ && coverage run --source aio_adb_shell setup.py test && coverage report -m
after_success:
- coveralls
